/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 331e44a132fcca304bdf79205cfd327e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
