/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 34f30b52c1b8b2fdf89a883e7b8b65e0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "Transcriber";
	}
	interface Env {
		KV: KVNamespace;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		Transcriber: DurableObjectNamespace<import("./src/server").Transcriber>;
		R2_AUDIO_BUCKET: R2Bucket;
		AI: Ai;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
