/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 183c911baab9d5abe7fcb24b54882831)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "Transcriber";
	}
	interface Env {
		KV: KVNamespace;
		VITE_SAMPLE_EP_1_ID: string;
		VITE_SAMPLE_EP_1_TITLE: string;
		VITE_SAMPLE_EP_2_ID: string;
		VITE_SAMPLE_EP_2_TITLE: string;
		VITE_SAMPLE_EP_3_ID: string;
		VITE_SAMPLE_EP_3_TITLE: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		Transcriber: DurableObjectNamespace<import("./src/server").Transcriber>;
		R2_AUDIO_BUCKET: R2Bucket;
		AI: Ai;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SAMPLE_EP_1_ID" | "VITE_SAMPLE_EP_1_TITLE" | "VITE_SAMPLE_EP_2_ID" | "VITE_SAMPLE_EP_2_TITLE" | "VITE_SAMPLE_EP_3_ID" | "VITE_SAMPLE_EP_3_TITLE">> {}
}
